version: "3.7"

services:
  web:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    networks: 
      - native-php
    container_name: apache
    restart: unless-stopped
    depends_on:
     - db
    ports:
      - "8082:80"
    networks: 
      - native-php
    volumes:
      - ./app:/var/www/html/

  db:
    image: mysql:5.7.29
    networks: 
      - native-php
    container_name: mysql-5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - "6033:3306"
    environment:
      MYSQL_DATABASE: school_management
      MYSQL_USER: tony_admin
      MYSQL_PASSWORD: sch00LM@n@g3m3nt
      MYSQL_ROOT_PASSWORD: sch00LM@n@g3m3nt
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql

  caching:
    image: redis:6-alpine
    networks: 
      - native-php
    container_name: redis-6-alpine
    ports:
      - 9736:6379
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 9736

networks:
  native-php:


      